### ISSUE TITLE
how can i keep generating new address even if there are unused address in wallet

### ISSUE THREAD

**Issue by rajlcx** [tango-crypto/cardano-wallet-js#1]
I want to generate new address for users, so if there are unused address in wallet, it keeps showing me same address.

**Comment by leobel** [comment]
Hi @rajlcx, cardano-wallet uses [BIP-44 standard](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Address_gap_limit) which returns at least 20 consecutive unused addresses (at the end of the list `wallet.getAddresses()`). You can use the method `wallet.getNextAddress()` and it will return the "next" unused address (which comes after the last unused in the 20 consecutive). Also if you want to keep going and generate more unused addresses you have `getAddressAt(index)` which you can use at `index = (await wallet.getAddresses()).length` and continue after that

**Comment by rajlcx** [comment]
> Hi @rajlcx, cardano-wallet uses [BIP-44 standard](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Address_gap_limit) which returns at least 20 consecutive unused addresses (at the end of the list `wallet.getAddresses()`). You can use the method `wallet.getNextAddress()` and it will return the "next" unused address (which comes after the last unused in the 20 consecutive). Also if you want to keep going and generate more unused addresses you have `getAddressAt(index)` which you can use at `index = (await wallet.getAddresses()).length` and continue after that

This works, but sometimes it gets stuck to the same address. However this is working I will check the issue from my side.
