### ISSUE TITLE
Create Or Restore Shelley Wallet Return an unknown error

### ISSUE THREAD

**Issue by liranAtli** [tango-crypto/cardano-wallet-js#12]
Hey, 
I am trying to do some simple requests with the "createOrRestoreShelleyWallet" method and I just copy and paste your example.
I don't know why and how this error showing to me over and over for any of my requests.

I downloaded the docker-compose file from 

`wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
`

if it helps to understand this is my code :)

**MY CODE**

`import { WalletServer, Seed } from "cardano-wallet-js";`

` const walletServer = WalletServer.init('http://kubernetes.docker.internal:8090/v2');
  const seedPhrase = Seed.generateRecoveryPhrase();
  const words = Seed.toMnemonicList(seedPhrase);
  const passphrase = "touchngo";
  const name = "touchngo-wallet"; `

 ` try {
    await walletServer.createOrRestoreShelleyWallet(name, words, passphrase);
  } catch (e) {
    return res.send({
      error: e
    });
  } `
  
 `
  return res.send({
    name: name,
    passphrase: passphrase,
    seed: seedPhrase,
    asArray: words,
  }); `

**ERROR RESPONSE**

`{
    "name": {
        "message": "Request failed with status code 400",
        "name": "Error",
        "stack": "Error: Request failed with status code 400\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
        "config": {
            "url": "http://kubernetes.docker.internal:8090/v2/wallets",
            "method": "post",
            "data": "\"{\\\"name\\\":\\\"touchngo-wallet\\\",\\\"mnemonic_sentence\\\":[\\\"candy\\\",\\\"chimney\\\",\\\"hat\\\",\\\"nuclear\\\",\\\"category\\\",\\\"crane\\\",\\\"pilot\\\",\\\"prevent\\\",\\\"hunt\\\",\\\"finish\\\",\\\"know\\\",\\\"list\\\",\\\"spin\\\",\\\"adult\\\",\\\"anxiety\\\"],\\\"passphrase\\\":\\\"touchngo\\\"}\"",
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "Content-Type": "application/json",
                "User-Agent": "axios/0.21.2",
                "Content-Length": 240
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1,
            "transitional": {
                "silentJSONParsing": true,
                "forcedJSONParsing": true,
                "clarifyTimeoutError": false
            }
        }
    }
}`

@javiertc @leobel 

Some Help :)

**Comment by liranAtli** [comment]
SOLVED - typescript version

` "typescript": "^3.6.4"`

**Comment by javiertc** [comment]
Good, closing this issue.
