### ISSUE TITLE
Send Payment Error : Error in $.payments[0]: parsing AddressAmount failed, key 'address' not found

### ISSUE THREAD

**Issue by rajqumar** [tango-crypto/cardano-wallet-js#2]
`let transaction = await wallet.sendPayment(passPhrase, ['addr_test1qqv72nksylexf5k36wgmavqw6m3sa0aps87l8m5t6lrfkds6aappsusgazmtu3dpzj9g0fe7agsrzxccpt59qgcxawfqp80cme'], ['1000000'], metadata);
console.log(transaction);
`
I am getting the above error in send payment.

**Comment by javiertc** [comment]
Hi rajqumar, 

Could you try to remove the single quote(') from the amount, like this:
['addr_test1qqv72nksylexf5k36wgmavqw6m3sa0aps87l8m5t6lrfkds6aappsusgazmtu3dpzj9g0fe7agsrzxccpt59qgcxawfqp80cme'], [1000000], metadata); 

Let me know if it helps.

**Comment by rajqumar** [comment]
> Hi rajqumar,
> 
> Could you try to remove the single quote(') from the amount, like this:
> `['addr_test1qqv72nksylexf5k36wgmavqw6m3sa0aps87l8m5t6lrfkds6aappsusgazmtu3dpzj9g0fe7agsrzxccpt59qgcxawfqp80cme'], [1000000], metadata); `
> 
> Let me know if it helps.

Removed but same issue, the data in api shows this on call => 
`      data: '{"passphrase":"passwordishere","payments":[{"amount":{"unit":"lovelace","quantity":1000000}}],"metadata":{"0":{"string":"abc"},"1":{"string":"2512a00e9653fe49a44a5886202e24d77eeb998f"},"2":{"int":123}}}',`

**Comment by leobel** [comment]
Hi @rajqumar, I just fixed the documentation, try creating the address list like this:
`let addresses = [new AddressWallet('addr_test1qqv72nksylexf5k36wgmavqw6m3sa0aps87l8m5t6lrfkds6aappsusgazmtu3dpzj9g0fe7agsrzxccpt59qgcxawfqp80cme')];`
