### ISSUE TITLE
Flaky server connectivity

### ISSUE THREAD

**Issue by 34r7h** [tango-crypto/cardano-wallet-js#20]
I love the simplicity of using docker compose to get going. Big time saver. Hey I guess this is a general problem with cardano tech but wondering if you run into:

```network > cardano-wallet_1  | [cardano-wallet.network:Warning:332] [2021-11-02 12:30:04.23 UTC] Couldn't connect to... ``` 

often and how y'all deal with it. Maybe there's a bigger list of nodes to connect to somewhere and we can pass in some yaml to docker compose command?

**Comment by 34r7h** [comment]
I suspect the flags advised in this solution are an answer to the above problem. Not sure how to add this through the docker compose command..
https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032/60

**Comment by leobel** [comment]
Hi @34r7h, sorry but I don't think could help to much here :(
