### ISSUE TITLE
Minting multiple token problems

### ISSUE THREAD

**Issue by conarwelsh** [tango-crypto/cardano-wallet-js#21]
First of all thanks for your work on this!

I am trying to mint multiple tokens, and for whatever reason it will only actually mint one of them (the last in the list to be precise).  Maybe I am structuring the tx wrong but I cannot seem to narrow it down.  

The tx builds, sends, receives, just as I would expect, except for the fact that only one asset ends up being included in the final transaction.  Any help even pointing me in the right direction would be greatly appreciated as I am stuck!!!

```js
const rootKey = Seed.deriveRootKey(this.configService.get("cardano.recoveryPhrase"))
const senderAddr = this.getSenderFromTx(tx)
const data = this.getTokenMetaData(items)
const metadata = Seed.buildTransactionMetadata(data)

let assets = []
const tokens = items.map(item => {
  const asset = new AssetWallet(this.policy.policyId, item.name, 1)
  assets.push(asset)
  return new TokenWallet(asset, this.policy.script, [this.policy.keyPair])
})

const minLovelace = Seed.getMinUtxoValueWithAssets(assets)
const coinSelection = await this.wallet.wallet.getCoinSelection([new AddressWallet(senderAddr)], [minLovelace], data)
const signingKeys = coinSelection.inputs.map(i => {
  return Seed.deriveKey(rootKey, i.derivation_path).to_raw_key()
})
tokens.filter(t => t.scriptKeyPairs).forEach(t => signingKeys.push(...t.scriptKeyPairs.map(k => k.privateKey.to_raw_key())))

coinSelection.outputs = coinSelection.outputs.map(output => {
  if(output.address === senderAddr) {
    output.assets = tokens.map(t => {
      return {
        policy_id: t.asset.policy_id,
        asset_name: Buffer.from(t.asset.asset_name).toString("hex"),
        quantity: t.asset.quantity,
      }
    })
  }
  return output
})

const txBody = Seed.buildTransactionWithToken(coinSelection, this.policy.ttl, tokens, signingKeys, {
  data,
})
const scripts = tokens.map(t => t.script) 
const finalTx = Seed.sign(txBody, signingKeys, metadata, scripts)
const signed = Buffer.from(finalTx.to_bytes()).toString("hex")
return this.walletService.submitTx(signed)
```

**Comment by ruben-rodrigues** [comment]
Yes, I think I found the issue. It's not working that well if you try to mint tokens under the same policy but with different asset names. The affected functions are `buildMultiAssets` and `buildTransactionMint`. Both functions should be grouping assets with different names but same policy under the same policy key, but they are being overwritten - that's why only the last one counts.

**Comment by leobel** [comment]
> Yes, I think I found the issue. It's not working that well if you try to mint tokens under the same policy but with different asset names. The affected functions are `buildMultiAssets` and `buildTransactionMint`. Both functions should be grouping assets with different names but same policy under the same policy key, but they are being overwritten - that's why only the last one counts.

Hi, sorry for the late reply. @ruben-rodrigues you're right this is a known bug I'm working on. Next release will fix it

**Comment by leobel** [comment]
Hi, please check latest version 1.3.2. It has that bug fixed among new features such as multi-sig
