### ISSUE TITLE
Not getting all transactions when calling wallet.getTransactions()

### ISSUE THREAD

**Issue by Ashwin1011** [tango-crypto/cardano-wallet-js#24]
Here are the screenshots of the wallet in nodejs and Yoroi app wallet. Yoroi wallet shows total 9 transactions but the node wallet only shows 5.
I can also see the difference in balances too. Yoroi wallet shows correct balance but node wallet shows balance of only those transactions.

![Screenshot from 2021-12-13 18-23-10](https://user-images.githubusercontent.com/49445626/145816947-f2c33654-9c8e-4c03-ba5c-9adaa4ff0b40.png)
![IMG_4280](https://user-images.githubusercontent.com/49445626/145817013-63e117ac-4064-4b58-a4cc-cfad3f58123d.PNG)
![IMG_4279](https://user-images.githubusercontent.com/49445626/145817030-440ffccc-6a96-40e5-aa28-04bff1c91bb0.PNG)

**Comment by leobel** [comment]
Hi @Ashwin1011 are you sure your wallet is fully sync? This is testnet/mainnet? I cannot see entirely the code of the first image but it seems to me you're applying some kind of filter there right? (`start` and `end` date).

**Comment by Ashwin1011** [comment]
Hi @leobel, Yes. The wallet is fully synced. The filter is was to filter out the incoming transactions but the code has been commented out. The start date is 1st Jan 2021 and the end date is the current Date(). I created the wallet nearly 2-3 months ago. So I should get all the transactions. I'm attaching some more screenshots. Please have a look. 
![Screenshot from 2021-12-14 11-26-39](https://user-images.githubusercontent.com/49445626/145953565-fff1d2f4-4571-4242-9c66-10cf5342bb01.png)

**Comment by Ashwin1011** [comment]
Issue resolved. Just had to increase the address_pool_gap while restoring wallet. Thanks for the help.
