### ISSUE TITLE
How long do you guys sync the full node by <docker-composer up>? 

### ISSUE THREAD

**Issue by btfdip** [tango-crypto/cardano-wallet-js#26]
from my side, it takes me two days and got stuck at 80% progress. 

Any potential reason and solution?

**Comment by btfdip** [comment]
![image](https://user-images.githubusercontent.com/96004784/147384745-ddf3ea2d-f867-40cb-9484-686afff21b5c.png)

**Comment by leobel** [comment]
Hi, normally it dones't take to much as you describe, but I guess it dependes of your setup.
