### ISSUE TITLE
Questions regarding underlaying components

### ISSUE THREAD

**Issue by zxpectre** [tango-crypto/cardano-wallet-js#3]
Hi guys! I've met you at 1st Open Mic Event, and having tryied to avoid at all cost cardano-wallet-cli, and that means I've tryied cardano-wallet, cardano-rosetta and cardano-serialization-lib-nodejs, I wish to know how are you building, signing, minting and submitting txs? Are you using cardano-wallet-cli underneath? or cardano-serialization-lib and using cardano-wallet api to submit?

Also, I stopped using cardano-wallet because for most payment platforms, accounts need to be drained and coin-selection and 1 ada change was killing me, I need to have freedom at selecting inputs and outputs when building transactions to be able to empty wallets.

What would be nice is if I could derive addresses myself (not using API) and avoid creating cardano-wallet accounts to have plenty of addresses without the overhead of wallet syncing.

And finally, what is the license?

Please, do you have good news for me? I'm willing to start all over for the last time to try your SDK ! :)

**Comment by leobel** [comment]
Hi @zxpectre you can use this SDK both depending on cardano-wallet or not. Right now we don't have any way to construct the tx inputs/outputs without using cardano-wallet, so we rely on `getCoinSelection` which basically calls the API endpoint [selectCoins](https://input-output-hk.github.io/cardano-wallet/api/edge/#tag/Coin-Selections) (we are working to bring this implementation on the SDK core so you can use it without a wallet instance). If you provide the tx structure (a `CoinSelectionWallet` instance), you can sign and mint it off-chain (this SDK uses cardano-serialization-lib underneath). 

For minting, you just need to provide a `CoinSelectionWallet` instance (if you rely on this SDK right now is only available through cardano-wallet) and the SDK will construct the final tx using cardano-serialization-lib. 

Also, you have a couple of methods to derive by yourself, check the key handling section [here](https://github.com/tango-crypto/cardano-wallet-js/blob/master/README.md#key-handling). For example, you can derive the root key from the recover phrase:
`let rootKey = Seed.deriveRootKey(phrase);` and then start deriving keys using some specific methods: `let accountKey = Seed.deriveAccountKey(rootKey, 0);` or just passing the entire path like this: `let privateKey = Seed.deriveKey(rootKey, ['1852H','1815H','0H','0','0']).to_raw_key();`

**NOTE**: Of course you can follow your own implementation to select the inputs/outputs but cardano-wallet implementation follow the best approach as described [here](https://iohk.io/en/blog/posts/2018/07/03/self-organisation-in-coin-selection/). As I said above, our idea is to include this algorithm inside the SDK and remove the dependence on cardano-wallet. Then you will be able to pass a list of addresses from where the tx inputs/outputs will be selected (similar to how is handled in Yorio wallet) this way you can keep your private keys always off-chain.

**Comment by zxpectre** [comment]
Thank you very much @leobel for this extensive explanation,  this sdk is really powerfull, please yes, try to avoid using cardano-wallet coin selection when posible, make it optional maybe, as cardano-wallet coin selection always left some spare change to be used lately, and a lot of payment integrations shouldn't use that user wallet feature, as payment integrations would need to drain addresses completely sending change (gains) to  addresses not derived under the same root keys. There are a couple of more reasons to avoid using cardano-wallet for "hot wallets".

I've managed this days to fully solve my needs other way around, but I will like to use this SDK some day as is a very complete swiss army knife for cardano devs, I've seen the code, totaly recomend it.

**Comment by leobel** [comment]
thanks @zxpectre, as I said you can build your own tx passing inputs/outputs and so on. What we want to definitely add is the possibility to generate that structure (that contains everything: inputs, outputs, change, etc) without the need of a wallet instance, but also a simple method to get the UTXOs for an address so you can build the tx they way you want.
