### ISSUE TITLE
estimateFee returns 403

### ISSUE THREAD

**Issue by skliarovartem** [tango-crypto/cardano-wallet-js#43]
What can be a reason of 403 for `estimateFee` request? Thanks!

**Comment by skliarovartem** [comment]
well, because the amount to send was to small, but don't have any idea why it is 403...

**Comment by skliarovartem** [comment]
yes, it was exactly because of small amount, and 403 was returning from cardano wallet(not your sdk). I was trying to reproduce it directly in cardanno wallet server by using `cardano-wallet` and it was the same result 403. so problem is that error status code is not so informative, it must be 400 or 420, but not 403

**Comment by javiertc** [comment]
Yes unfortunately cardano-wallet is not very informative with errors.
