### ISSUE TITLE
sendPayment() not considering metadata being passed

### ISSUE THREAD

**Issue by jac1013** [tango-crypto/cardano-wallet-js#5]
Hi @leobel I'm trying to create a transaction with `sendPayment()` function and according to the code, the last parameter (the forth one, which is optional) it's the metadata to add to the transaction, however, I'm passing an object in that parameter and the transaction ends up without metadata, here's a transaction I created with this function: [cardano-explorer-testnet](https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=b03fb176f0a02ffd118734d5bbaf4eef3fb9030abb81951fe29557ddf1e96e67)

Here's the example of my code (I confirmed that metadata is not `undefined`).

```JavaScript
const transaction = await wallet.sendPayment(
      passphrase,
      addresses,
      amounts,
      { o: metadata.choiceId, i: metadata.iv, c: metadata.content },
    );
```

I don't seem to be doing anything wrong, I'm doing exactly as the documentation says and I also saw in the tests that apparently this is the correct way [here](https://github.com/tango-crypto/cardano-wallet-js/blob/master/test/wallet.ts#L1496) 

The metadata is not in the assertions tho.

Thanks in advance!

**Comment by leobel** [comment]
Hi @jac1013 according to the doc [here](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransaction)

> All top-level keys must be integers between 0 and 2^64 - 1

So since your metadata top-level keys aren't integers that's what you get empty metadata. If you want to keep your original structure consider add a wrapper object with an integer key and inside put your metadata e.g. 

```
let metadata = {
   0: { o: metadata.choiceId, i: metadata.iv, c: metadata.content }
}
```

**Comment by jac1013** [comment]
@leobel you are right, and I remember reading something related to this in this library documentation. Thanks for pointing that out.

I think this other one is really an issue, when using metadata, the function `getTransactions()` won't retrieve metadata information, and I believe the reason is, metadata is not being extracted from the response:

https://github.com/tango-crypto/cardano-wallet-js/blob/master/wallet/transaction-wallet.ts#L51

That `from` function is not extracting the metadata from the response, neither the metadata is being set elsewhere. Hoperfully I'm not mistaken in this one and I'm helping with bug hunting. When I call `getTransactions()` they come without the metadata, same with `getTransaction()` both functions are using the same `from` mapper.

**Comment by jac1013** [comment]
Hey @leobel just FYI, so the problem is, the library right now, has a mechanism to convert an `any` object to Cardano Metadata, however, there's no way to reverse it, I couldn't find a function that converts Cardano Metadata into the `any` object that was passed. I did my homework here to see if I can help with this. I believe I'll have to hack it around so I can receive the metadata and parse it myself.

Here's part of the solution: https://github.com/jac1013/cardano-wallet-js/blob/master/wallet/transaction-wallet.ts#L53, however, this doesn't fix the whole problem (only partially, at least we can receive the raw metadata from Cardano) because we received the `{0: {...}, 1:{...}}` object, which was not what we provided (the parsing needs to be done). I tried all the construction functions for metadata in `utils.ts` but after reading their code I saw that they are to transform an `{}` any object into `{0: {...}, 1: {...} ...}` Cardano's Metadata JSON Schema and not the other way around. I hope this helps.

**Comment by leobel** [comment]
Hi @jac1013 you're right, we aren't handling the metadata mapping back, I'll try to implement it ASAP.

**Comment by leobel** [comment]
Hi @jac1013 check out version 1.2.0 the transactions will come with the metadata on Cardano's Metadata JSON but you can "reverse" it back using `Seed.reverseMetadata(data: any, type = "object")`. `type` parameter is optional and you can pass `array` if you want to get an Array in the top-level object instead of `{}`.
