### ISSUE TITLE
getTransactions() function is showing only internal txs

### ISSUE THREAD

**Issue by rajqumar** [tango-crypto/cardano-wallet-js#6]
When I am making any transactions from address generated by my wallet it is showing in getTransactions function, but when any transaction is made from other wallet address or any external wallet it is not showing.

Please check, I am using this function, I have also tested using start and end date, the issue is same for this =>
`let transactions = await wallet.getTransactions()`

**Comment by leobel** [comment]
Hi @rajqumar are you using it on testnet? Are you sure the wallet is 100% in sync? Also, can you share the txIds that aren't not showing on your wallet? I've checked it and I can't reproduce the issue.

**Comment by rajqumar** [comment]
> Hi @rajqumar are you using it on testnet? Are you sure the wallet server is 100% in sync (check `let information = await walletServer.getNetworkInformation();` it should return `{... "sync_progress": { "status": "ready" } }`)? Also, can you share the txIds that aren't showing on your wallet? I've checked it and I can't reproduce the issue.

The node is completely synced and status shows ready.

I am generating wallet enterprise address with the code below.

`let rootKey = Seed.deriveRootKey(recoveryPhrase);
let stakePrvKey = Seed.deriveKey(rootKey, ['1852H', '1815H', '0H', '2', 25]);
const stakePubKey = stakePrvKey.to_raw_key().to_public();
const EnterpriseAddr = EnterpriseAddress.new(
    NetworkInfo.testnet().network_id(),
    StakeCredential.from_keyhash(stakePubKey.hash())
)
.to_address().to_bech32();
console.log(EnterpriseAddr)`

**Comment by rajqumar** [comment]
There are 20 unused addresses in wallet, suppose I generate a new address at index 21, it does not show in address list, how can I add this address in wallet ?

**Comment by leobel** [comment]
The addresses are not generated, there are already there, you are just "discovering" it. If you want to get more addresses on the list you need to send some money to any unused address and more will be listed. Since the wallet follows de BIP44 protocol it will stop discovering addresses (return it on the list) once 20 unused addresses are found in a row.

**Comment by leobel** [comment]
This is useful for example when the wallet calculates the balance, it will stop counting when 20 unused addresses are found. So if you send money to an address coming after the 20 mentioned above it won't count in the final balance since it won't be taken into account.

**Comment by rajqumar** [comment]
> This is useful for example when the wallet calculates the balance, it will stop counting when 20 unused addresses are found. So if you send money to an address coming after the 20 mentioned above it won't count in the final balance since it won't be taken into account.

So what if I send money to 20 addresses, and then discover more addresses and send money will they be added in wallet and final balance will show the amount ?

**Comment by leobel** [comment]
If the addresses receiving money are separated for no more than 20 unused addresses in a row, they'll all show up in the balance. As I said before the wallet will stop looking for UTXO's after 20 **CONSECUTIVE** unused addresses are found.

**Comment by rajqumar** [comment]
> If the addresses receiving money are separated for no more than 20 unused addresses in a row, they'll all show up in the balance. As I said before the wallet will stop looking for UTXO's after 20 **CONSECUTIVE** unused addresses are found.

Ok, I understood the wallet mechanism
