### ISSUE TITLE
wallet.getCoinSelection() guidance

### ISSUE THREAD

**Issue by 34r7h** [tango-crypto/cardano-wallet-js#7]
Is there an option to only return addresses with unspent utxo? I come across an addressAmount error or similar payments[1] error after passing in the return from wallet.getAddresses().

Please explain, when we slice(0,1) are we only getting the first address and if so how does the coin requirement get covered if other addresses are needed to fulfill.

Thanks guys. Great work here!

**Comment by leobel** [comment]
> Is there an option to only return addresses with unspent utxo? 
You can use `wallet.getUsedAddresses()`

> Please explain, when we slice(0,1) are we only getting the first address and if so how does the coin requirement get covered if other addresses are needed to fulfill.

I don't know your context, but if you're taking it from the doc, these are only illustrative examples

**Comment by 34r7h** [comment]
cheers, I mean addresses that have ADA to avoid payment addressAmount error or payments[1] error when coinselect sees an empty address
